//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteBanHang.CSDL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SanPham()
        {
            this.CTPhieuNhap = new HashSet<CTPhieuNhap>();
            this.CTHoaDon = new HashSet<CTHoaDon>();
        }
    
        public string MaSP { get; set; }
        public string TenSP { get; set; }
        public string HinhDD { get; set; }
        public int SoLuong { get; set; }
        public string MoTaCT { get; set; }
        public Nullable<double> GiaBan { get; set; }
        public Nullable<bool> PhoBien { get; set; }
        public Nullable<System.DateTime> NgayDang { get; set; }
        public string MaNCC { get; set; }
        public string MaDM { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTPhieuNhap> CTPhieuNhap { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTHoaDon> CTHoaDon { get; set; }
        public virtual DanhMuc DanhMuc { get; set; }
        public virtual NhaCungCap NhaCungCap { get; set; }
    }
}
